

#[cfg(target_family = "unix")]
pub const FREE_MONO_FONT_DATA: &[u8] = include_bytes!("assets/fonts/FreeMono.ttf");

#[cfg(target_family = "unix")]
pub const TERRAIN_PLAIN_IMG_DATA: &[u8] = include_bytes!("assets/terrains/plain.png");
#[cfg(target_family = "unix")]
pub const TERRAIN_SWAMP_IMG_DATA: &[u8] = include_bytes!("assets/terrains/swamp.png");
#[cfg(target_family = "unix")]
pub const TERRAIN_WALL_IMG_DATA: &[u8] = include_bytes!("assets/terrains/wall.png");

#[cfg(target_family = "unix")]
pub const RESOURCE_SOURCE_IMG_DATA: &[u8] = include_bytes!("assets/resources/source.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_HYDROGEN_IMG_DATA: &[u8] = include_bytes!("assets/resources/H.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_OXYGEN_IMG_DATA: &[u8] = include_bytes!("assets/resources/O.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_KEANIUM_IMG_DATA: &[u8] = include_bytes!("assets/resources/K.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_LEMERGIUM_IMG_DATA: &[u8] = include_bytes!("assets/resources/L.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_UTRIUM_IMG_DATA: &[u8] = include_bytes!("assets/resources/U.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_ZYNTHIUM_IMG_DATA: &[u8] = include_bytes!("assets/resources/Z.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_CATALYST_IMG_DATA: &[u8] = include_bytes!("assets/resources/X.png");
#[cfg(target_family = "unix")]
pub const RESOURCE_UNKNOWN_IMG_DATA: &[u8] = include_bytes!("assets/resources/unknown.png");

#[cfg(target_family = "unix")]
pub const STRUCTURE_CONSTRUCTEDWALL_IMG_DATA: &[u8] = include_bytes!("assets/structures/constructedWall.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_CONTAINER_IMG_DATA: &[u8] = include_bytes!("assets/structures/container.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_CONTROLLER_IMG_DATA: &[u8] = include_bytes!("assets/structures/controller.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_EXTENSION_IMG_DATA: &[u8] = include_bytes!("assets/structures/extension.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_EXTRACTOR_IMG_DATA: &[u8] = include_bytes!("assets/structures/extractor.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_FACTORY_IMG_DATA: &[u8] = include_bytes!("assets/structures/factory.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_LAB_IMG_DATA: &[u8] = include_bytes!("assets/structures/lab.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_LINK_IMG_DATA: &[u8] = include_bytes!("assets/structures/link.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_NUKER_IMG_DATA: &[u8] = include_bytes!("assets/structures/nuker.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_OBSERVER_IMG_DATA: &[u8] = include_bytes!("assets/structures/observer.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_POWERSPAWN_IMG_DATA: &[u8] = include_bytes!("assets/structures/powerSpawn.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_RAMPART_IMG_DATA: &[u8] = include_bytes!("assets/structures/rampart.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_ROAD_IMG_DATA: &[u8] = include_bytes!("assets/structures/road.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_SPAWN_IMG_DATA: &[u8] = include_bytes!("assets/structures/spawn.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_STORAGE_IMG_DATA: &[u8] = include_bytes!("assets/structures/storage.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_TERMINAL_IMG_DATA: &[u8] = include_bytes!("assets/structures/terminal.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_TOWER_IMG_DATA: &[u8] = include_bytes!("assets/structures/tower.png");
#[cfg(target_family = "unix")]
pub const STRUCTURE_UNKNOWN_IMG_DATA: &[u8] = include_bytes!("assets/structures/icon.png");


#[cfg(target_family = "windows")]
pub const FREE_MONO_FONT_DATA: &[u8] = include_bytes!(r"assets\fonts\FreeMono.ttf");

#[cfg(target_family = "windows")]
pub const TERRAIN_PLAIN_IMG_DATA: &[u8] = include_bytes!(r"assets\terrains\plain.png");
#[cfg(target_family = "windows")]
pub const TERRAIN_SWAMP_IMG_DATA: &[u8] = include_bytes!(r"assets\terrains\swamp.png");
#[cfg(target_family = "windows")]
pub const TERRAIN_WALL_IMG_DATA: &[u8] = include_bytes!(r"assets\terrains\wall.png");

#[cfg(target_family = "windows")]
pub const RESOURCE_SOURCE_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\source.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_HYDROGEN_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\H.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_OXYGEN_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\O.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_KEANIUM_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\K.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_LEMERGIUM_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\L.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_UTRIUM_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\U.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_ZYNTHIUM_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\Z.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_CATALYST_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\X.png");
#[cfg(target_family = "windows")]
pub const RESOURCE_UNKNOWN_IMG_DATA: &[u8] = include_bytes!(r"assets\resources\unknown.png");

#[cfg(target_family = "windows")]
pub const STRUCTURE_CONSTRUCTEDWALL_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\constructedWall.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_CONTAINER_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\container.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_CONTROLLER_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\controller.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_EXTENSION_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\extension.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_EXTRACTOR_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\extractor.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_FACTORY_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\factory.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_LAB_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\lab.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_LINK_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\link.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_NUKER_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\nuker.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_OBSERVER_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\observer.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_POWERSPAWN_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\powerSpawn.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_RAMPART_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\rampart.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_ROAD_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\road.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_SPAWN_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\spawn.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_STORAGE_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\storage.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_TERMINAL_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\terminal.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_TOWER_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\tower.png");
#[cfg(target_family = "windows")]
pub const STRUCTURE_UNKNOWN_IMG_DATA: &[u8] = include_bytes!(r"assets\structures\icon.png");
